# permissions for end users to view msdatadrivenautoscalings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: msdatadrivenautoscaling-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: msdda-autoscaler-operator
    app.kubernetes.io/part-of: msdda-autoscaler-operator
    app.kubernetes.io/managed-by: kustomize
  name: msdatadrivenautoscaling-viewer-role
rules:
- apiGroups:
  - scaling.msdda.com
  resources:
  - msdatadrivenautoscalings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scaling.msdda.com
  resources:
  - msdatadrivenautoscalings/status
  verbs:
  - get
