# permissions for end users to edit msdatadrivenautoscalings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: msdatadrivenautoscaling-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: msdda-autoscaler-operator
    app.kubernetes.io/part-of: msdda-autoscaler-operator
    app.kubernetes.io/managed-by: kustomize
  name: msdatadrivenautoscaling-editor-role
rules:
- apiGroups:
  - scaling.msdda.com
  resources:
  - msdatadrivenautoscalings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaling.msdda.com
  resources:
  - msdatadrivenautoscalings/status
  verbs:
  - get
