---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: msdatadrivenautoscalings.scaling.msdda.com
spec:
  group: scaling.msdda.com
  names:
    kind: MSDataDrivenAutoscaling
    listKind: MSDataDrivenAutoscalingList
    plural: msdatadrivenautoscalings
    singular: msdatadrivenautoscaling
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: MSDataDrivenAutoscaling is the Schema for the msdatadrivenautoscalings API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of MSDataDrivenAutoscaling
            type: object
            required:
              - microservices
            properties:
              microservices:
                description: List of microservices to monitor
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: Microservice Name
                    sla:
                      description: SLA (Service Level Agreement) Requirements
                      type: object
                      required:
                        - strategy
                      properties:
                        strategy:
                          type: string
                          description: Declares the type of strategy we want to addopt
                          enum: 
                            - 'Conservative'
                            - 'Normal'
                            - 'BestEffort'
                          default: 'Conservative'
                    modelRequirements:
                      description: Autoscaling Model requirements
                      type: object
                      required:
                        - scalingStrategy
                      properties:
                        scalingStrategy:
                          type: string
                          description: Scaling Strategy to be used, reactive/proactive/any
                          enum: 
                            - 'proactive'
                            - 'reactive'
                            - 'any'
                          default: 'any'                      
                    serverRequirements:
                      description: MicroService specific requirements
                      type: object
                      required:
                        - serverType
                        - startupOptimization
                      properties:
                        serverType:
                          type: string
                          description: Declares the top level domain that will be used for configuring all Routes in this deployment
                          enum: 
                            - 'liberty'
                            - 'gunicorn'
                            - 'apache'
                            - 'nodejs'
                            - 'tomcat'
                        startupOptimization:
                          type: boolean
                          description: Whether we should apply built-in startup optimization configuration
                        scalingType:
                          type: string
                          description: MicroService can scale either vertically, horizontally or both.
                          enum: 
                            - 'horizontal'
                            - 'vertical'
                            - 'any'
                          default: 'any'                      
                        customMetrics:
                          type: string
                          description: ID of the metric to be used by prometheus
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status defines the observed state of MSDataDrivenAutoscaling
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
